
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RPAREN_LBRACE = 11;
  public static final int STRING_LITERAL = 13;
  public static final int EOF = 0;
  public static final int PREFIX = 5;
  public static final int CONCAT = 7;
  public static final int IF = 3;
  public static final int ELSE = 4;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RPAREN = 10;
  public static final int IDENTIFIER = 12;
  public static final int SUFFIX = 6;
  public static final int LPAREN = 9;
  public static final int RBRACE = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "IF",
  "ELSE",
  "PREFIX",
  "SUFFIX",
  "CONCAT",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "RPAREN_LBRACE",
  "IDENTIFIER",
  "STRING_LITERAL"
  };
}

